import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { createUser,checkUser } from './authAPI';
import { updateUser } from '../user/userAPI';
import { signOut,checkAuth } from './authAPI';
const initialState = {
  loggedInUserToken: null,
  status: 'idle',
  error:null,
  // userChecked:false
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const createUserAsync = createAsyncThunk(
  'user/createUser',
  async (userData) => {
    const response = await createUser(userData);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);



export const checkUserAsync = createAsyncThunk(
  'user/checkUser',
  async (loginInfo,{rejectWithValue}) => {
    try
    {const response = await checkUser(loginInfo);
    return response.data;
    }
    catch(error){
      console.log(error);
      return rejectWithValue(error);
    }
  }
);

// export const checkAuthAsync = createAsyncThunk(
//   'user/checkAuth',
//   async () => {
//     try {
//       const response = await checkAuth();
//       return response.data;
//     } catch (error) {
//       console.log(error);
//     }
//   }
// );

export const signOutAsync = createAsyncThunk(
  'user/signOut',
  async (loginInfo) => {
    const response = await signOut(loginInfo);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);


export const authSlice = createSlice({
  name: 'user',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(createUserAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(createUserAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.loggedInUserToken = action.payload;
      })
      .addCase(checkUserAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(checkUserAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.loggedInUserToken = action.payload;
      })
      .addCase(checkUserAsync.rejected, (state, action) => {
        state.status = 'idle';
        state.error = action.payload;
      })
        .addCase(signOutAsync.pending, (state) => {
          state.status = 'loading';
        })
      .addCase(signOutAsync.fulfilled, (state, action) => {
          state.status = 'idle'; 
          state.loggedInUserToken = null;
        })
        // .addCase(checkAuthAsync.pending, (state) => {
        //   state.status = 'loading';
        // })
        // .addCase(checkAuthAsync.fulfilled, (state, action) => {
        //   state.status = 'idle';
        //   state.loggedInUserToken = action.payload;
        //   state.userChecked = true;
        // })
        // .addCase(checkAuthAsync.rejected, (state, action) => {
        //   state.status = 'idle';
        //   state.userChecked = true;
        // })
  },
});

export const selectLoggedInUser=(state)=>state.auth.loggedInUserToken;
export const selectError=(state)=>state.auth.error;
// export const selectUserChecked = (state) => state.auth.userChecked;

export const { increment } = authSlice.actions;
export default authSlice.reducer;
